#:schema node_modules/wrangler/config-schema.json
name = "storage"
main = "src/index.ts"
compatibility_date = "2024-04-05"
compatibility_flags = ["nodejs_compat"]

# Fill in the account ID from the Cloudflare dashboard below.
account_id = "ec9b597fa02615ca6a0e62b7ff35d0cc"
workers_dev = true

# Deploy an R2 bucket from the Cloudflare dashboard and fill in bucket_name.
[[r2_buckets]]
binding = 'R2'
bucket_name = 'sandbox'
preview_bucket_name = 'sandbox-preview'

# KEY is required but can be set to any secret string.
[vars]
KEY = '123456'
